name: bug test sundar 1
description: Tests out env settings
branding:
  icon: activity
  color: blue

inputs:
  - name: ProductionEnvReviewer
    type: string
  - name: DeploySecret
    type: string
    is_secret: true
  
configs:
  environments: 
    - name: staging
      parameters: 
        protected-branches: false
        custom-branch-policies:
          - main/*
          - releases/*
        wait-timer: 50
        reviewers:
          - name: ${{ inputs.ProductionEnvReviewer }}
            type: User
        secrets:
          - name: DeploySecret
            value: ${{ inputs.DeploySecret }}
            
    - name: prod
      parameters: 
        custom-branch-policies:
          - main/*
          - releases/*
        reviewers:
          - name: ${{ inputs.ProductionEnvReviewer }}
            type: User

