name: bug test sundar 1
description: Tests out env settings
branding:
  icon: activity
  color: blue

inputs:
  - name: ProductionEnvReviewer
    type: string
  - name: DeploySecret
    type: string
    is-secret: true
  
configs:
  environments: 
    - name: env1
      parameters: 
        protected-branches: false

    - name: env2
      parameters: 
        custom-branch-policies:
          - main/*
          - releases*

    - name: env3
      parameters: 
        wait-timer: 50

    - name: env4
      parameters: 
        reviewers:
          - name: ${{ inputs.ProductionEnvReviewer }}
            type: User

    - name: env5
      parameters: 
        secrets:
          - name: DeploySecret
            value: ${{ inputs.DeploySecret }}

    - name: env6
      parameters: 
        reviewers:
          - name: ${{ inputs.ProductionEnvReviewer }}
            type: User
        secrets:
          - name: DeploySecret
            value: ${{ inputs.DeploySecret }}

    - name: staging
      parameters: 
        protected-branches: false
        custom-branch-policies:
          - main/*
          - releases/*
        wait-timer: 50
        reviewers:
          - name: ${{ inputs.ProductionEnvReviewer }}
            type: User
        secrets:
          - name: DeploySecret
            value: ${{ inputs.DeploySecret }}
            
    - name: prod
      parameters: 
        custom-branch-policies:
          - main/*
          - releases/*
        reviewers:
          - name: ${{ inputs.ProductionEnvReviewer }}
            type: User

